export const ADD_QUESTION = "ADD_QUESTION";
export const ADD_RESPONSE = "ADD_RESPONSE";
export const REMOVE_RESPONSE = "REMOVE_RESPONSE";
export const REMOVE_SINGLE_RESPONSE = "REMOVE_SINGLE_RESPONSE";

export const ADD_FULLNAME_RESPONSE = "ADD_FULLNAME_RESPONSE";
export const REMOVE_FULLNAME_RESPONSE = "REMOVE_FULLNAME_RESPONSE";
export const ADD_INSTITUTION_RESPONSE = "ADD_INSTITUTION_RESPONSE";
export const REMOVE_INSTITUTION_RESPONSE = "REMOVE_INSTITUTION_RESPONSE";
export const ADD_EMAIL_RESPONSE = "ADD_EMAIL_RESPONSE";
export const REMOVE_EMAIL_RESPONSE = "REMOVE_EMAIL_RESPONSE";
export const ADD_PHONE_RESPONSE = "ADD_PHONE_RESPONSE";
export const REMOVE_PHONE_RESPONSE = "REMOVE_PHONE_RESPONSE";