export const UPDATE_TICKET_BOARD = "UPDATE_TICKET_BOARD";
export const GET_TICKET_BOARD = "GET_TICKET_BOARD";
export const SET_TICKETS = "SET_TICKETS";
export const UPDATE_TICKET_STATUS = "UPDATE_TICKET_STATUS";
export const UPDATE_TICKET_DESCRIPTION = "UPDATE_TICKET_DESCRIPTION";

export const SET_ACTIVE_TICKET = "SET_ACTIVE_TICKET";

export const ASSIGN_USER = "ASSIGN_USER";
export const UNASSIGN_USER = "UNASSIGN_USER";

export const GET_SERVICE_COST = "GET_SERVICE_COST";
export const SET_SERVICE_COST = "SET_SERVICE_COST";
export const REMOVE_SERVICE_COST = "REMOVE_SERVICE_COST";
export const POST_SERVICE_COST = "POST_SERVICE_COST";