export const UPDATE_TICKET_BOARD = "UPDATE_TICKET_BOARD";
export const GET_TICKET_BOARD = "GET_TICKET_BOARD";
export const SET_TICKETS = "SET_TICKETS";
export const UPDATE_TICKET_STATUS = "UPDATE_TICKET_STATUS";