import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import Divider from "../Divider";
import "./index.css";
import uuid from "react-uuid";
import {
  ADD_RESPONSE,
  REMOVE_SINGLE_RESPONSE,
} from "../../redux/actions/formActions";

function Dropdown({ question }) {
  const dispatch = useDispatch();
  const answerList = useSelector((state) => state.questionReducer.answerList);
  const [options, setOptions] = useState([]);
  const [selectedValue, setSelectedValue] = useState(null);
  const handleChange = (event) => {
    const selected = JSON.parse(event.target.value);
    dispatch({
      type: REMOVE_SINGLE_RESPONSE,
      payload: {
        question: question,
      },
    });
    dispatch({
      type: ADD_RESPONSE,
      payload: {
        id: uuid(),
        response: selected.answer,
        question: selected,
      },
    });
    setSelectedValue(selected);
  };

  useEffect(() => {
    let optionList = answerList[question.question_id ?? ""] ?? [];
    optionList = optionList.sort((a, b) => {
      let fa = a.added_on;
      let fb = b.added_on;

      if (Number(fa)) {
        //sort autogenerated options
        if (+fa < +fb) {
          return -1;
        }
        if (+fa > +fb) {
          return 1;
        }
        return 0;
      }

      if (fa < fb) {
        return -1;
      }
      if (fa > fb) {
        return 1;
      }
      return 0;
    });
    setOptions(optionList);
  }, [answerList, question]);

  return (
    <div className="GlobalCustomerQuestionContainer">
      <div className="GlobalQuestionTitle">
        {question.question}{" "}
        <p style={{ color: "red" }}>{question.mandatory ? "*" : ""}</p>
      </div>
      <div className="customer__component__subtitle">{question.question_note}</div>
      <select className="select" onChange={handleChange}>
        {selectedValue === null && <option key={"Default"} value={""} />}
        {options.map((option) => (
          <option key={option.answer_id} value={JSON.stringify(option)}>
            {option.answer}
          </option>
        ))}
      </select>
      <Divider />
    </div>
  );
}

export default Dropdown;
