// Input:
// - List of all answers
// - Question Object
// Output:
// - List of options sorted by the created time
function getQuestionOptions(answerList, question) {
  var optionList = answerList[question.question_id ?? ""] ?? [];
  optionList = optionList.sort((a, b) => {
    let fa = a.added_on;
    let fb = b.added_on;

    if (Number(fa)) {
      //sort autogenerated options
      if (+fa < +fb) {
        return -1;
      }
      if (+fa > +fb) {
        return 1;
      }
      return 0;
    }

    if (fa < fb) {
      return -1;
    }
    if (fa > fb) {
      return 1;
    }
    return 0;
  });
  optionList = optionList.filter((option) => option !== "");
  return optionList;
}

export { getQuestionOptions };
