name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the release branch
  push:
    branches: [ release ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            DIR="/home/ec2-user/labby"
            pm2 delete all
            cd /home/ec2-user
            
            if [ ! -d $DIR ]
            then
              mkdir labby &&
              git clone https://github.com/ubclaunchpad/labby.git labby &&
              cd labby/backend &&
              yarn
            else
              cd labby/backend
              yarn
            fi
            
            git checkout release &&
            git fetch --all &&
            git reset --hard origin/release &&
            git pull origin release &&
            yarn &&
            pm2 start index.js
          '
